version: '3'

networks:
  chatbot:
    name: infra_chatbot
    driver: bridge
  
services:
  nginx:
    image: nginx:1.20.0
    networks:
      - chatbot
    restart: always
    ports:
      - "8000:80"
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  redis:
    image: redis:6.2.6
    networks:
      - chatbot
    restart: always
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"