version: "3.8"

networks:
  kwsnet:
    name: infra_kwsnet
    driver: bridge
  minecraft:
    name: infra_minecraft
    driver: bridge
  chatbot:
    name: infra_chatbot
    driver: bridge

services:
  web:
    build: ./nginx
    image: nginx_kwsnet
    container_name: nginx-kwsnet-container
    networks:
      - kwsnet
      - minecraft
      - chatbot
    restart: always
    volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/data:/var/www/certbot
        - ./well-known:/usr/share/nginx/well-known
        - /home/festival/web:/usr/share/nginx/festival
        - /home/stories2/KangnamShuttle4.0/codeserver/vscode2/config/workspace/God-Money/build/web:/usr/share/nginx/God-Money
    ports:
        - 80:80
        - 443:443
  redis:
    image: redis:6.2.6
    container_name: redis-kwsnet-container
    networks:
      - infra_chatbot
      - infra_kwsnet
    restart: always
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  certbot:
    image: certbot/certbot:v1.20.0
    command: certonly --noninteractive --agree-tos -d kws1.gapmoe.net --register-unsafely-without-email --webroot -w /var/www/well-known/
    volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/logs:/var/log/letsencrypt
        - ./certbot/data:/var/www/certbot
        - ./well-known:/var/www/well-known
  certbot2:
    image: certbot/certbot:v1.20.0
    command: certonly --noninteractive --agree-tos -d kws1.kangnam.ac.kr --register-unsafely-without-email --webroot -w /var/www/well-known/
    volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/logs:/var/log/letsencrypt
        - ./certbot/data:/var/www/certbot
        - ./well-known:/var/www/well-known
