version: "3.8"

networks:
  kwsnet:
    name: infra_kwsnet
    driver: bridge
  minecraft:
    name: infra_minecraft
    driver: bridge

services:
  web:
    build: ./nginx
    image: nginx_kwsnet
    container_name: nginx-kwsnet-container
    networks:
      - kwsnet
      - minecraft
    restart: always
    volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/data:/var/www/certbot
        - ./well-known:/usr/share/nginx/well-known
    ports:
        - 80:80
        - 443:443
  certbot:
    image: certbot/certbot:v1.20.0
    command: certonly --noninteractive --agree-tos -d kws1.gapmoe.net --register-unsafely-without-email --webroot -w /var/www/well-known/
    volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/logs:/var/log/letsencrypt
        - ./certbot/data:/var/www/certbot
        - ./well-known:/var/www/well-known
